# Fingerprint Uniqueness Checker Configuration

# Dataset settings
dataset:
  base_path: "fingerprint_data/IRIS and FINGERPRINT DATASET/fingerprint_data"
  image_format: "BMP"
  subjects_range: [1, 45]  # Number of subjects in dataset
  fingers_per_subject: 10  # 5 fingers from each hand
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1

# Image preprocessing
preprocessing:
  target_size: [224, 224]  # Standard size for CNN input
  normalization: true
  augmentation: true
  rotation_range: 15
  zoom_range: 0.1
  brightness_range: 0.2
  contrast_range: 0.2

# Siamese Network settings
siamese_network:
  embedding_dim: 128
  margin: 1.0  # Contrastive loss margin
  learning_rate: 0.001
  batch_size: 32
  epochs: 100
  early_stopping_patience: 10
  model_save_path: "models/siamese_fingerprint_model.h5"

# Feature extraction
feature_extraction:
  use_minutiae: true
  use_texture: true
  use_ridge_orientation: true
  minutiae_threshold: 0.5
  texture_window_size: 16

# Database settings
database:
  type: "postgresql"  # postgresql, mysql, sqlite
  host: "localhost"
  port: 5432
  database: "fingerprint_db"
  username: "fingerprint_user"
  password: "password123"
  table_name: "fingerprints"
  similarity_threshold: 0.85  # Threshold for duplicate detection
  max_similarity_score: 0.95
  connection_pool_size: 10
  max_connections: 20

# Verification settings
verification:
  similarity_algorithm: "cosine"  # cosine, euclidean, manhattan
  min_matching_score: 0.8
  max_verification_time: 5.0  # seconds
  enable_cache: true
  cache_size: 1000

# Performance settings
performance:
  use_gpu: true
  num_workers: 4
  prefetch_factor: 2
  pin_memory: true

# Logging settings
logging:
  level: "INFO"
  file: "fingerprint_checker.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Output settings
output:
  save_results: true
  results_path: "results/"
  save_visualizations: true
  visualization_path: "visualizations/" 