# Duplicate Fingerprint Detection Configuration
# Using Bozorth3 algorithm, xytheta format, and Boyer-Moore pattern matching

# Database Configuration
database:
  type: "postgresql"
  host: "localhost"
  port: 5432
  database: "fingerprint_db"
  username: "fingerprint_user"
  password: "your_secure_password"
  table_name: "fingerprints"
  connection_pool_size: 10
  max_connections: 20
  similarity_threshold: 0.85
  max_similarity_score: 0.95

# Bozorth3 Algorithm Configuration
bozorth3:
  max_distance: 20.0          # Maximum distance between corresponding minutiae points (pixels)
  max_angle_diff: 30.0        # Maximum angle difference between corresponding minutiae (degrees)
  min_matches: 12             # Minimum number of matching minutiae for a match
  max_score: 100.0            # Maximum Bozorth3 score
  distance_tolerance: 5.0     # Tolerance for pairwise distance matching (pixels)
  angle_weight: 0.1           # Weight for angle difference in scoring

# Boyer-Moore Pattern Matching Configuration
boyer_moore:
  pattern_length: 20          # Length of pattern to use for Boyer-Moore matching
  x_bin_size: 10.0            # Bin size for x-coordinate discretization (pixels)
  y_bin_size: 10.0            # Bin size for y-coordinate discretization (pixels)
  theta_bin_size: 15.0        # Bin size for theta discretization (degrees)
  min_pattern_matches: 1      # Minimum number of pattern matches required

# Minutiae Extraction Configuration
minutiae_extraction:
  min_minutiae_count: 5       # Minimum number of minutiae required
  max_minutiae_count: 100     # Maximum number of minutiae to extract
  quality_threshold: 0.3      # Minimum quality score for minutiae
  gabor_kernel_size: 15       # Gabor filter kernel size
  gabor_sigma: 2.0            # Gabor filter sigma
  gabor_lambda: 10.0          # Gabor filter lambda
  gabor_gamma: 0.5            # Gabor filter gamma

# Image Preprocessing Configuration
preprocessing:
  resize_width: 512           # Target width for image resizing
  resize_height: 512          # Target height for image resizing
  gaussian_blur_kernel: 3     # Gaussian blur kernel size
  histogram_equalization: true # Enable histogram equalization
  morphological_operations: true # Enable morphological operations
  noise_reduction: true       # Enable noise reduction

# Duplicate Detection Configuration
duplicate_detection:
  similarity_threshold: 0.85  # Overall similarity threshold for duplicate detection
  min_match_score: 12         # Minimum Bozorth3 match score
  max_processing_time: 300    # Maximum processing time per comparison (seconds)
  batch_size: 100             # Number of files to process in each batch
  enable_parallel_processing: false # Enable parallel processing (experimental)
  save_xytheta_files: true    # Save xytheta format files for duplicates
  save_detailed_results: true # Save detailed matching results

# Logging Configuration
logging:
  level: "INFO"               # Logging level (DEBUG, INFO, WARNING, ERROR)
  file: "duplicate_detection.log" # Log file name
  max_file_size: "10MB"       # Maximum log file size
  backup_count: 5             # Number of backup log files
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Output Configuration
output:
  results_directory: "duplicate_results"  # Directory for saving results
  save_json_results: true     # Save results in JSON format
  save_summary_report: true   # Save summary report in text format
  save_xytheta_files: true    # Save xytheta format files
  save_visualizations: false  # Save visualization images (if available)
  compress_results: false     # Compress output files

# Performance Configuration
performance:
  enable_caching: true        # Enable result caching
  cache_size: 1000            # Maximum cache size
  cache_ttl: 3600             # Cache time-to-live (seconds)
  memory_limit: "2GB"         # Memory usage limit
  cpu_limit: 4                # Maximum CPU cores to use

# Validation Configuration
validation:
  validate_input_files: true  # Validate input fingerprint files
  check_file_format: true     # Check file format compatibility
  verify_minutiae_quality: true # Verify minutiae quality
  min_file_size: 1024         # Minimum file size in bytes
  max_file_size: "10MB"       # Maximum file size

# Security Configuration
security:
  enable_file_checksums: true # Enable file checksum verification
  hash_algorithm: "sha256"    # Hash algorithm for checksums
  validate_file_integrity: true # Validate file integrity
  secure_file_handling: true  # Enable secure file handling

# Error Handling Configuration
error_handling:
  max_retries: 3              # Maximum number of retries for failed operations
  retry_delay: 1.0            # Delay between retries (seconds)
  continue_on_error: true     # Continue processing on non-critical errors
  log_errors: true            # Log all errors
  save_error_reports: true    # Save detailed error reports 